params:
  seed: 0 

  algo: 
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space: 
      continuous: 
        mu_activation: None 
        sigma_activation: None 

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [32, 32]
      activation: tanh
      d2rl: False 
          
      initializer: 
        name: default
      regularizer: 
        name: default

  load_checkpoint: False
  load_path: "" 

  config:
    name: twip
    full_experiment_name: twip 0.0.1
    env_name: generic
    multi_gpu: False
    ppo: True 
    mixed_precision: True
    normalize_input: False
    normalize_value: True
    value_bootstrap: True

    num_actors: 1 
    reward_shaper: 
      scale_value: 0.01

    normalize_advantage: True 
    gamma: 0.99 
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive 
    schedule_legacy: legacy 
    kl_threshold: 0.008
    score_to_win: 2000
    max_epochs: 1000
    save_best_after: 200
    save_frequency: 50
    grad_norm: 1.0 
    entropy_coef: 0
    trucante_grad: False
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 1
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    player:
    games_num: 2000







